spring:
  application:
    name: study-cafe

  kafka:
    producer:
      bootstrap-servers: localhost:9092 # Kafka 클러스터에 대한 초기 연결에 사용할 호스트 : 포트 목록
      ## serializer 방법은 KafkaProducerConfig 로 설정
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer