name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Docker 이미지 빌드
    - name: Build Docker Image
      run: |
        docker build -t my-app:latest .

    # Docker 이미지 아카이브
    - name: Save Docker Image as tar
      run: |
        docker save my-app:latest -o my-app.tar

    # 아카이브 파일을 아티팩트로 업로드
    - name: Upload Docker Image as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-image
        path: my-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write # AWS EKS에 배포 시 필요할 수 있음

    steps:
    - uses: actions/checkout@v4
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # 서울 리전으로 설정

    # EC2에 SSH로 접속하여 배포 (필요한 경우)
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@ec2-54-180-236-111.ap-northeast-2.compute.amazonaws.com << 'EOF'
          # Docker 이미지 아카이브 다운로드 후 로드
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} my-app.tar ec2-user@ec2-54-180-236-111.ap-northeast-2.compute.amazonaws.com:~/
          docker load -i my-app.tar
          docker run -d -p 80:8080 my-app:latest
        EOF
